apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers }}
  KAFKA_TOPIC: {{ .Values.kafka.topic }}
  KAFKA_GROUP_ID: {{ .Values.kafka.groupId }}
  REDIS_MASTER: {{ .Values.redis.master }}
  REDIS_SENTINELS: {{ .Values.redis.sentinels }}
  S3_BUCKET: {{ .Values.s3.bucket }}
  AWS_REGION: {{ .Values.aws.region }}
  DB_HOST: {{ .Values.db.host }}
  DB_NAME: {{ .Values.db.name }}
  DB_USER: {{ .Values.db.user }}
  SPRING_PROFILES_ACTIVE: {{ .Values.springProfile }}
