cluster:
  imageName: ghcr.io/cloudnative-pg/postgresql:13.20
  # HA: 1 primary + 2 replica
  instances: 3

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "1GB"
      work_mem: "32MB"
      wal_level: "logical"
      max_replication_slots: "10"
      max_wal_senders: "10"
      hot_standby: "on"

  storage:
    size: 100Gi
    storageClass: gp3

  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 4000m
      memory: 8Gi

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname

  monitoring:
    enabled: true

  backup:
    enabled: true
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: s3://my-bucket/cnpg/prod
      s3Credentials:
        accessKeyId:
          name: cnpg-s3-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-s3-secret
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        encryption: AES256

  superuserSecret:
    name: cnpg-superuser-secret
