repositories:
  - name: cnpg
    url: https://cloudnative-pg.github.io/charts

releases:
  - name: cnpg-operator
    namespace: cnpg-system
    createNamespace: true
    chart: cnpg/cloudnative-pg
    version: "0.22.0"
    values:
      - values/{{ .Environment.Name }}/operator.yaml
